from prompts.shared_prompt import COMMON_SYSTEM_PROMPT
from prompts.main_agent_prompt import MAIN_AGENT_SYSTEM_PROMPT
from prompts.db_prompt import (
    DATABASE_MANAGER_SYSTEM_PROMPT,
    RDMS_SYSTEM_PROMPT,
    NOSQL_SYSTEM_PROMPT,
    REDIS_SYSTEM_PROMPT,
)
from prompts.api_prompt import (
    API_MANAGER_SYSTEM_PROMPT,
    REST_SYSTEM_PROMPT,
    GRAPHQL_SYSTEM_PROMPT,
    GRPC_SYSTEM_PROMPT,
    SOAP_SYSTEM_PROMPT,
)
from prompts.code_review_prompt import CODE_REVIEW_SYSTEM_PROMPT

__all__ = [
    "COMMON_SYSTEM_PROMPT",
    "MAIN_AGENT_SYSTEM_PROMPT",
    "DATABASE_MANAGER_SYSTEM_PROMPT",
    "RDMS_SYSTEM_PROMPT",
    "NOSQL_SYSTEM_PROMPT",
    "REDIS_SYSTEM_PROMPT",
    "API_MANAGER_SYSTEM_PROMPT",
    "REST_SYSTEM_PROMPT",
    "GRAPHQL_SYSTEM_PROMPT",
    "GRPC_SYSTEM_PROMPT",
    "SOAP_SYSTEM_PROMPT",
    "CODE_REVIEW_SYSTEM_PROMPT",
]
