"""Internal prompt templates for engineeringstack."""

from .api_prompt import (
    API_MANAGER_SYSTEM_PROMPT,
    REST_SYSTEM_PROMPT,
    GRAPHQL_SYSTEM_PROMPT,
    GRPC_SYSTEM_PROMPT,
    SOAP_SYSTEM_PROMPT,
)
from .db_prompt import (
    DATABASE_MANAGER_SYSTEM_PROMPT,
    RDBMS_SYSTEM_PROMPT,
    NOSQL_SYSTEM_PROMPT,
    REDIS_SYSTEM_PROMPT,
)
from .code_review_prompt import CODE_REVIEW_SYSTEM_PROMPT
from .helper_prompt import (
    HELPER_MANAGER_SYSTEM_PROMPT,
    CODING_AGENT_SYSTEM_PROMPT,
)
from .main_agent_prompt import MAIN_AGENT_SYSTEM_PROMPT
from .shared_prompt import COMMON_SYSTEM_PROMPT

__all__ = [
    "API_MANAGER_SYSTEM_PROMPT",
    "REST_SYSTEM_PROMPT",
    "GRAPHQL_SYSTEM_PROMPT",
    "GRPC_SYSTEM_PROMPT",
    "SOAP_SYSTEM_PROMPT",
    "DATABASE_MANAGER_SYSTEM_PROMPT",
    "RDBMS_SYSTEM_PROMPT",
    "NOSQL_SYSTEM_PROMPT",
    "REDIS_SYSTEM_PROMPT",
    "CODE_REVIEW_SYSTEM_PROMPT",
    "HELPER_MANAGER_SYSTEM_PROMPT",
    "CODING_AGENT_SYSTEM_PROMPT",
    "MAIN_AGENT_SYSTEM_PROMPT",
    "COMMON_SYSTEM_PROMPT",
]

